# required
cluster_name         = "zelig"
domain_name          = "blue.cloud"
region_name          = "us-south"
zone_name            = "us-south-2"
data_center_name     = "dal06"
cluster_key          = "../../secrets/cluster-key.rsa"
bastion_key          = "../../secrets/bastion-key.rsa"
pull_secret          = "../../secrets/pull-secret.txt"
resource_group_name  = "ibm/j4zzcat"
transient_gateway_id = "81dd3319-75c3-43e2-a02f-41b4a6bbc6d3"
