variable name              {}
variable profile           {}
variable vpc_name          {}
variable cluster_name      {}
variable domain_name       {}
variable subnet_id         {}
variable keys              {}
variable nameserver_ip     {}
variable resource_group_id {}
variable security_groups   {}
