#! /bin/bash

function do_help {
  cat <<EOT
NAME:
  mule - control IBM Cloud Command Line (cli) docker

USAGE:
  mule (build|run)

EOT
  exit 1
}

function do_build {
  exec docker build --rm -f ${IMAGE_FILE} -t ${IMAGE_NAME}:${IMAGE_VERSION} .
}

function do_run {
  IC_API_KEY=$(           security find-generic-password -l 'ibmcloud-api-key' -w )
  IAAS_CLASSIC_USERNAME=$(security find-generic-password -l 'ibmcloud-iaas-classic-api-key' | awk -F '=' '/acct/{print substr($2,2,length($2)-2)}')
  IAAS_CLASSIC_API_KEY=$( security find-generic-password -l 'ibmcloud-iaas-classic-api-key' -w )

  IC_TIMEOUT=60
  IAAS_CLASSIC_TIMEOUT=60

  exec docker run -it --rm \
    -v $(pwd):/cwd \
    -e IC_API_KEY=${IC_API_KEY} \
    -e IBMCLOUD_API_KEY=${IC_API_KEY} \
    -e IAAS_CLASSIC_USERNAME=${IAAS_CLASSIC_USERNAME} \
    -e IAAS_CLASSIC_API_KEY=${IAAS_CLASSIC_API_KEY} \
    -e IC_TIMEOUT=${IC_TIMEOUT} \
    -e IAAS_CLASSIC_TIMEOUT=${IAAS_CLASSIC_TIMEOUT} \
    ${IMAGE_NAME}:${IMAGE_VERSION}
}

SCRIPT_DIR=$(cd $(dirname "${0}"); pwd -P)
IMAGE_FILE=${SCRIPT_DIR}/ibmcloud-cli.dockerfile
IMAGE_NAME=$(   cat ${IMAGE_FILE} | awk -F '"' '/image.name/{print $2}')
IMAGE_VERSION=$(cat ${IMAGE_FILE} | awk -F '"' '/image.version/{print $2}')

cmd=${1}
case ${cmd} in
  build) do_build ;;
  run)   do_run ;;
  *)     do_help ;;
esac
