#! /bin/bash

SCRIPT_DIR=$(cd $(dirname "${0}"); pwd -P)

IMAGE_FILE=${SCRIPT_DIR}/ibmcloud-cli.dockerfile
IMAGE_NAME=$(   cat ${IMAGE_FILE} | awk -F '"' '/image.name/{print $2}')
IMAGE_VERSION=$(cat ${IMAGE_FILE} | awk -F '"' '/image.version/{print $2}')

IC_API_KEY=$(           security find-generic-password -l 'ibmcloud-api-key' -w )
IAAS_CLASSIC_USERNAME=$(security find-generic-password -l 'ibmcloud-iaas-classic-api-key' | awk -F '=' '/acct/{print substr($2,2,length($2)-2)}')
IAAS_CLASSIC_API_KEY=$( security find-generic-password -l 'ibmcloud-iaas-classic-api-key' -w )

IC_TIMEOUT=60
SL_TIMEOUT=60
IAAS_CLASSIC_TIMEOUT=60

docker run -it --rm \
  -v $(pwd):/cwd \
  -e IC_API_KEY=${IC_API_KEY} \
  -e IBMCLOUD_API_KEY=${IC_API_KEY} \
  -e IAAS_CLASSIC_USERNAME=${IAAS_CLASSIC_USERNAME} \
  -e IAAS_CLASSIC_API_KEY=${IAAS_CLASSIC_API_KEY} \
  -e IC_TIMEOUT=${IC_TIMEOUT} \
  -e SL_TIMEOUT=${SL_TIMEOUT} \
  -e IAAS_CLASSIC_TIMEOUT=${IAAS_CLASSIC_TIMEOUT} \
  ${IMAGE_NAME}:${IMAGE_VERSION}
