variable name              {}
variable profile           {}
variable vpc_name          {}
variable cluster_name      {}
variable domain_name       {}
variable subnet_id         {}
variable key_id            {}
variable resource_group_id {}
variable security_groups   {}
