
Vagrant.configure( '2' ) do | config |
  config.vm.box = 'generic/ubuntu1804'

  config.vm.provider 'virtualbox' do | vb |
    vb.name = 'ipxe-testbed'
    vb.gui = false
    vb.cpus = 4
    vb.memory = 4096
  end
  config.vm.network :public_network, :bridge => 'en1: Wi-Fi (AirPort)'

  config.vm.provision 'infra', type: 'shell', inline: <<-SHELL
    export DEBIAN_FRONTEND=noninteractive
  SHELL
end
